In [0]:
import numpy as np

arr = np.random.normal(loc = 1, scale = 100, size = (1000, 50))
avg = np.mean(arr, axis=0)
dev = np.std(arr, axis=0)
for j in range(50):
  for i in range(1000):
    arr[i][j] = (arr[i][j]-avg[j])/dev[j]
summ = np.sum(arr, axis=1)
for i in range (len(summ)):
  if summ[i]>10:
    print(i)

A = np.eye(3)    
B = np.eye(3)
C = np.vstack((A,B))
print(C)

1
25
27
49
58
109
120
127
136
169
205
208
212
213
216
227
231
241
248
252
260
284
294
300
328
340
344
362
366
410
432
443
455
464
466
469
483
484
490
494
498
499
532
542
562
581
612
618
625
635
640
651
654
693
718
724
743
752
757
772
798
808
818
832
836
888
893
894
898
920
932
953
959
993
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [0]:
import pandas 

data = pandas.read_csv('titanic.csv', index_col='PassengerId')
data[:10]



srvd = data['Survived'].value_counts(1)
#????
print(srvd)



0    0.616162
1    0.383838
Name: Survived, dtype: float64
